#!/bin/sh

# copy the plugin.xml file
cp -v plugin.xml out/production/at-migration
cp -v README.md out/production/at-migration

cd out/production/at-migration

zip -rv scriptAT.zip . -i \*.class *.bsh *.xml *.md -x test/*

mv -v scriptAT.zip C:/"Program Files (x86)"/"Archivists Toolkit 2.0"/plugins

# create a zip of the source code
cd ../../..

zip -vr scriptAT_src.zip src -x "*.svn*" "*.DS_Store*"